# Generated by Django 3.0.8 on 2020-11-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_app', '0002_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='orderNumber',
            field=models.IntegerField(),
        ),
    ]
